const INITIAL_REMAINING_TIME = 60;
const ONE_PLAYER_QUIZ_LENGTH = 15;
const TWO_PLAYER_QUIZ_LENGTH = 30;
const MAX_NAME_LENGTH = 8;

module.exports = {
    INITIAL_REMAINING_TIME,
    ONE_PLAYER_QUIZ_LENGTH,
    TWO_PLAYER_QUIZ_LENGTH,
    MAX_NAME_LENGTH,
};