module.exports = [
    {file: 'actions.png', name: 'Actions'},
    {file: 'akka.png', name: 'Akka'},
    {file: 'android.png', name: 'Android'},
    {file: 'angular.png', name: 'Angular'},
    {file: 'ansible.png', name: 'Ansible'},
    {file: 'apple.png', name: 'Apple'},
    {file: 'arduino.png', name: 'Arduino'},
    {file: 'aws.png', name: 'AWS'},
    {file: 'azure-active-directory.png', name: 'Azure AD'},
    {file: 'azure-cloud.png', name: 'Azure Cloud'},
    {file: 'azure-OMS-Log-Analytics.png', name: 'Azure Log Analytics'},
    {file: 'azure.png', name: 'Azure'},
    {file: 'cast-sdk.png', name: 'Cast Sdk'},
    {file: 'Chromecast.png', name: 'Chromecast'},
    {file: 'css3.png', name: 'CSS3'},
    {file: 'dialogflow-02.png', name: 'Dialogflow'},
    {file: 'docker.png', name: 'Docker'},
    {file: 'docker-registry.png', name: 'Docker Registry'},
    {file: 'ember.png', name: 'Ember'},
    {file: 'Firebase-Cloud-Functions.png', name: 'Cloud Functions'},
    {file: 'firebase.png', name: 'Firebase'},
    {file: 'flapjack.png', name: 'Flapjack'},
    {file: 'gatling-03.png', name: 'Gatling'},
    {file: 'github.png', name: 'Github'},
    {file: 'gitlab.png', name: 'GitLab'},
    {file: 'glusterfs.png', name: 'GlusterFS'},
    {file: 'gocd.png', name: 'GoCD'},
    {file: 'google-home-glamour-v1.png', name: 'Google Home'},
    {file: 'go.png', name: 'Go'},
    {file: 'grafana.png', name: 'Grafana'},
    {file: 'graphite.png', name: 'Graphite'},
    {file: 'hadoop.png', name: 'Hadoop'},
    {file: 'haproxy.png', name: 'HAProxy'},
    {file: 'hbase.png', name: 'HBase'},
    {file: 'hive.png', name: 'Hive'},
    {file: 'html5.png', name: 'HTML5'},
    {file: 'Influxdb.png', name: 'Influxdb'},
    {file: 'java.png', name: 'Java'},
    {file: 'jenkins.png', name: 'Jenkins'},
    {file: 'js.png', name: 'JS'},
    {file: 'kafka.png', name: 'Kafka'},
    {file: 'kotlin.png', name: 'Kotlin'},
    {file: 'liferay.png', name: 'Liferay'},
    {file: 'marathon.png', name: 'Marathon'},
    {file: 'mesos.png', name: 'Mesos'},
    {file: 'messenger.png', name: 'Messenger'},
    {file: 'mongodb.png', name: 'MongoDB'},
    {file: 'nexus.png', name: 'Nexus'},
    {file: 'nodejs-01.png', name: 'Node.JS'},
    {file: 'prometheus.png', name: 'Prometheus'},
    {file: 'python.png', name: 'Python'},
    {file: 'qlik.png', name: 'Qlik'},
    {file: 'rabbitmq.png', name: 'RabbitMQ'},
    {file: 'raspberry-pi-02.png', name: 'Raspberry Pi'},
    {file: 'react.png', name: 'React'},
    {file: 'redis.png', name: 'Redis'},
    {file: 'redux.png', name: 'Redux'},
    {file: 'scala.png', name: 'Scala'},
    {file: 'sonarqube.png', name: 'SonarQube'},
    {file: 'sqlserver.png', name: 'Sql Server'},
    {file: 'swift.png', name: 'Swift'},
    {file: 'terraform.png', name: 'Terraform'},
    {file: 'twitter.png', name: 'Twitter'},
    {file: 'vue.png', name: 'Vue.js'},
    {file: 'zookeeper.png', name: 'ZooKeeper'},
];
